# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # mount same apt archives folder for all boxes to save space
  config.vm.synced_folder "~/var/cache/apt/archives", "/var/cache/apt/archives"

  # enable use of vagrant insecure keypair
  config.ssh.insert_key = false
end
